name: "Test, Lint & Deploy"
on: [push, pull_request]
env:
  DIRENV_WARN_TIMEOUT: 5m
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: planet-a-ventures
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
  npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: planet-a-ventures
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Set version
        if: startsWith(github.ref, 'refs/tags/')
        run: devenv shell npm-version-from-git
      - name: Build
        run: devenv shell build
      - name: Archive generated npm package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: npm/
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: devenv shell publish
