name: "Test, Lint & Deploy"
on: [push, pull_request]
env:
  DIRENV_WARN_TIMEOUT: 5m
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - run: nix flake check --no-build
      - name: Install direnv with Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
      - name: Format check
        run: pre-commit run --all-files
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run test:update-snapshots
      - name: diff
        run: git diff --exit-code
  npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: npm install
        run: nix develop --command npm ci
      - name: Set version
        if: startsWith(github.ref, 'refs/tags/')
        run: nix develop --command npm --no-git-tag-version version from-git
      - name: Build
        run: nix develop --command npm run build
      - name: Archive generated npm package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: npm/
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: nix develop --ignore-environment --keep NODE_AUTH_TOKEN --command npm publish
