name: "Test, Lint & Deploy"
on: [push, pull_request]
env:
  DIRENV_WARN_TIMEOUT: 5m
permissions:
  contents: read
jobs:
  test:
    # Experimental snapshot testing requires macos-latest it seems; review this
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: planet-a-ventures
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: planet-a-ventures
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "TAG_VERSION=${VERSION#v}" >> $GITHUB_OUTPUT
      - name: Set version
        if: startsWith(github.ref, 'refs/tags/')
        run: devenv shell npm-version-from-git
      - name: Build
        run: devenv shell build
      - name: Package
        run: devenv shell package
      - name: Archive generated npm package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: planet-a-parcel-optimizer-versioned-imports-${{ steps.get_tag_version.outputs.TAG_VERSION }}.tgz
          if-no-files-found: error
  npm:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: planet-a-ventures
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "TAG_VERSION=${VERSION#v}" >> $GITHUB_OUTPUT
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Download generated npm package
        uses: actions/download-artifact@v4
        with:
          name: npm-package
          path: planet-a-parcel-optimizer-versioned-imports-${{ steps.get_tag_version.outputs.TAG_VERSION }}.tgz
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: devenv shell publish "planet-a-parcel-optimizer-versioned-imports-${{ steps.get_tag_version.outputs.TAG_VERSION }}.tgz"
